FROM openjdk:17-jdk-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y locales && \
    echo "ko_KR.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen ko_KR.UTF-8

ENV LANG=ko_KR.UTF-8
ENV LC_ALL=ko_KR.UTF-8
ENV DB_HOST host.docker.internal
ENV JAVA_TOOL_OPTIONS="-Duser.language=ko -Duser.region=KR"

# 작업 디렉토리 설정
WORKDIR /app

# 빌드된 jar 파일 복사 (파일 이름과 경로는 실제에 맞게 조정)
COPY ./build/libs/EduChat-0.0.1-SNAPSHOT.jar app.jar

# 컨테이너 내에서 애플리케이션이 사용하는 포트 (기본은 8080, 만약 애플리케이션 설정에서 8110을 사용한다면 그대로 사용)
EXPOSE 8080

# jar 파일 실행
CMD ["java", "-jar", "app.jar"]
