version: '3.8'

services:
  hltutor-be:
    build:
      context: .
      dockerfile: Dockerfile-be
    container_name: hltutor-be
    ports:
      - "8110:8080"
    depends_on:
      - discussion-redis-server

  discussion-redis-server:
    build:
      context: .
      dockerfile: Dockerfile-redis
    container_name: discussion-redis-server
    ports:
      - "6379:6379"
